### ISSUE TITLE
what goes in siteMetaData googleVerification

### ISSUE THREAD

**Issue by AbhimanyuAryan** [fabien0102/gatsby-starter#79]
I'm not sure what verification string you need here. I have added analytics code but i don't get this part. Can somehow help me with it?

**Comment by fabien0102** [comment]
Hello, sorry for the delay, I'm not really active anymore on this project ^^
You have more information over there -> https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-google-analytics

For the DNS verification, if my memory is good, it's something to set into your DNS provider to tell "this is my domain" to google. Usually it's a TXT entry to add with the verification string (careful, I don't set any google analytics since years, this have probably change, but everything should be explain somewhere in the google analytics documentation in a "getting started" section :wink: )

**Comment by jodylecompte** [comment]
Hi @AbhimanyuAryan,

As far as I know, the verification is only needed for proving ownership in search console (I think they call it webmaster tools now); for analytics I believe being able to place the analytics script itsself serves as proof of ownership for that side of things.
