### ISSUE TITLE
Allot of vulnerabilities in this repo

### ISSUE THREAD

**Issue by bentrynning** [fabien0102/gatsby-starter#84]
After installing this repo, npm reports allot of vulnerabilities in node_modules. Any suggestions if this should be checked?
```
added 3734 packages from 1489 contributors and audited 39108 packages in 91.283s
found 770 vulnerabilities (671 low, 71 moderate, 27 high, 1 critical)
```

Other than that, thanks for a perfect gatsby starter :)

**Comment by fabien0102** [comment]
Can be good to update the dependencies 😅 I don't know the exact vulnerabilities list, but it's often on the tooling part so not really on what you ship in production (so it's not really risky to use, since the code is not executed by somebody else than the developer itself 😉 )

(And sorry for the answer delay, I'm a bit out of track on this project… gatsby progress very quickly and I don't really have the time to follow anymore, at least I hope that this project give you some ideas of how to organize your project 😃)

**Comment by bensontrent** [comment]
#89 fixes security vulnerabilities.
